// Engine chain: Chrome's built-in on-device model first (free, private,
// zero-setup — ondevice.js), Vercel AI Gateway with the user's own key as the
// fallback (gateway.js). The old ChatGPT-tab-driving path is gone.
// factcheck.js rides on both and adds its own evidence retrieval.
// brand.js mints the per-load random OKLCH accent shared by every surface.
importScripts('brand.js', 'gateway.js', 'ondevice.js', 'factcheck.js');

// --- Brand colour -----------------------------------------------------------
// A fresh dull OKLCH colour each time the worker wakes (install or browser
// start). Stored so the popup, in-page UI and history all wear the same one,
// and painted onto the toolbar icon as a diamond.

function jcDrawBrandIcon(brand) {
  try {
    const [r, g, b] = jcBrandRgb(brand);
    const fill = `rgb(${r} ${g} ${b})`;
    const sizes = [16, 32, 48, 128];
    const imageData = {};
    for (const s of sizes) {
      const cv = new OffscreenCanvas(s, s);
      const ctx = cv.getContext('2d');
      ctx.clearRect(0, 0, s, s);
      ctx.fillStyle = fill;
      ctx.translate(s / 2, s / 2);
      ctx.rotate(Math.PI / 4); // square → diamond
      const d = s * 0.6;
      const rad = Math.max(1, s * 0.12);
      const x = -d / 2;
      ctx.beginPath();
      ctx.moveTo(x + rad, x);
      ctx.arcTo(x + d, x, x + d, x + d, rad);
      ctx.arcTo(x + d, x + d, x, x + d, rad);
      ctx.arcTo(x, x + d, x, x, rad);
      ctx.arcTo(x, x, x + d, x, rad);
      ctx.closePath();
      ctx.fill();
      imageData[s] = ctx.getImageData(0, 0, s, s);
    }
    chrome.action.setIcon({ imageData });
  } catch (_) {
    // OffscreenCanvas / setIcon unavailable — the static PNG icon stays.
  }
}

async function jcRefreshBrand() {
  const brand = jcRandomBrand();
  await chrome.storage.local.set({ jcBrand: brand });
  jcDrawBrandIcon(brand);
}

// Repaint the icon if the colour is (re)generated by any surface.
chrome.storage.onChanged.addListener((changes, area) => {
  if (area === 'local' && changes.jcBrand && changes.jcBrand.newValue) {
    jcDrawBrandIcon(changes.jcBrand.newValue);
  }
});
chrome.runtime.onStartup.addListener(jcRefreshBrand);

async function askEngine(prompt, reqId, tabId) {
  const availability = await onDeviceAvailability();
  const gateway = await gatewayGetSettings();

  if (availability === 'available') {
    const local = await onDeviceAsk(prompt, reqId, tabId);
    if (local) return local;
  } else if (availability === 'downloadable' || availability === 'downloading') {
    if (gateway) {
      // Answer via the Gateway now; pull the model down for next time.
      onDeviceWarmup();
    } else {
      // No key to fall back on — wait out the one-time download, with progress.
      const local = await onDeviceAsk(prompt, reqId, tabId);
      if (local) return local;
    }
  }

  if (!gateway && availability === 'unavailable') {
    const reason = await onDeviceBlockReason();
    return {
      ok: false,
      needsKey: true,
      reason: reason.kind,
      error:
        `${reason.headline}. ${reason.detail} ` +
        'To keep using JustClarify here, add your own AI Gateway key in the ' +
        'extension popup — answers then come from a hosted model instead.',
    };
  }

  // Has a key (or gatewayAsk will return its friendly no-key message).
  return gatewayAsk(prompt, reqId, tabId);
}

// --- Live audio session state -------------------------------------------------

let liveAudioTabId = null;
let liveAudioBuffer = [];
let liveAudioRun = 0;

// Spoken sentences arrive one at a time and are usually too short to check in
// isolation ("And that number is going up."). Hold them until there's a
// paragraph's worth of speech, then check that as a block — which also keeps
// verdict calls to a sane rate on a live stream.
const LIVE_AUDIO_BATCH_CHARS = 420;

function liveAudioReset() {
  liveAudioTabId = null;
  liveAudioBuffer = [];
}

function liveAudioCollect(text) {
  const line = String(text || '').trim();
  if (!line) return;
  liveAudioBuffer.push(line);
  const joined = liveAudioBuffer.join(' ');
  if (joined.length < LIVE_AUDIO_BATCH_CHARS) return;

  liveAudioBuffer = [];
  const tabId = liveAudioTabId;
  const runId = ++liveAudioRun;
  // Deliberately not awaited: transcription must keep flowing while this batch
  // is checked, and every result reaches the page by message anyway.
  factCheckText(joined, tabId, runId, 3).catch(() => {});
}

async function ensureOffscreen() {
  const existing = await chrome.runtime.getContexts({ contextTypes: ['OFFSCREEN_DOCUMENT'] });
  if (existing.length) return;
  await chrome.offscreen.createDocument({
    url: 'offscreen.html',
    reasons: ['USER_MEDIA'],
    justification: 'Transcribe tab audio so spoken claims can be fact-checked.',
  });
}

async function liveAudioBegin(tabId) {
  if (tabId == null) return { ok: false, error: 'No tab to listen to.' };

  const { jcDeepgramKey } = await chrome.storage.local.get(['jcDeepgramKey']);
  if (!jcDeepgramKey) {
    return {
      ok: false,
      error:
        'Live audio needs a Deepgram API key for transcription. Add one in the JustClarify popup.',
    };
  }

  await ensureOffscreen();
  // Single-use and short-lived: it must be minted here and handed straight over.
  const streamId = await chrome.tabCapture.getMediaStreamId({ targetTabId: tabId });

  const response = await chrome.runtime.sendMessage({
    target: 'offscreen',
    type: 'JC_AUDIO_START',
    streamId,
    apiKey: jcDeepgramKey,
    language: 'en',
  });

  if (!response?.ok) return response || { ok: false, error: 'Offscreen document did not start.' };
  liveAudioTabId = tabId;
  liveAudioBuffer = [];
  return { ok: true };
}

async function liveAudioEnd() {
  try {
    await chrome.runtime.sendMessage({ target: 'offscreen', type: 'JC_AUDIO_STOP' });
  } catch (_) {}
  // Check whatever was said before the user stopped rather than discarding it.
  const tail = liveAudioBuffer.join(' ').trim();
  if (tail.length > 80) factCheckText(tail, liveAudioTabId, ++liveAudioRun, 3).catch(() => {});
  liveAudioReset();
}

// ── Dictionary ────────────────────────────────────────────────────────────
// Define answers from a real dictionary, not the model: the Free Dictionary
// API (dictionaryapi.dev) is public, keyless and CC-licensed. A definition is
// a lookup, not a generation — the model can only paraphrase what a dictionary
// already states, and it can get it wrong. Returns { ok: false } for anything
// that isn't a plain English word, or a word with no entry, and the caller
// falls back to the model then.
const JC_DICT_URL = 'https://api.dictionaryapi.dev/api/v2/entries/en/';

// Mirrors the backend's is_single_word: no spaces, letters (hyphens allowed),
// ordinary casing so code identifiers like useEffect never hit the dictionary.
function jcIsDictionaryWord(text) {
  const word = String(text || '').trim().replace(/^[.,;:!?"'“”‘’()[\]]+|[.,;:!?"'“”‘’()[\]]+$/g, '');
  if (!word || /\s/.test(word)) return null;
  if (!/^[\p{L}-]+$/u.test(word)) return null;
  if (word.replace(/-/g, '').length < 2) return null;
  const bare = word.replace(/-/g, '');
  const ordinary = bare === bare.toLowerCase() || bare === bare.toUpperCase()
    || bare === bare[0].toUpperCase() + bare.slice(1).toLowerCase();
  return ordinary ? word : null;
}

async function lookupDictionary(rawWord) {
  const word = jcIsDictionaryWord(rawWord);
  if (!word) return { ok: false, error: 'not-a-word' };

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 4000);
  let data;
  try {
    const res = await fetch(JC_DICT_URL + encodeURIComponent(word.toLowerCase()), {
      signal: controller.signal,
    });
    if (!res.ok) return { ok: false, error: 'not-found' };
    data = await res.json();
  } catch (error) {
    return { ok: false, error: String(error) };
  } finally {
    clearTimeout(timeout);
  }
  if (!Array.isArray(data) || !data.length) return { ok: false, error: 'not-found' };

  // Flatten to at most three senses, each keeping its part of speech and the
  // dictionary's own example sentence when it has one.
  const senses = [];
  for (const entry of data) {
    for (const meaning of entry.meanings || []) {
      for (const def of meaning.definitions || []) {
        if (!def.definition) continue;
        senses.push({
          partOfSpeech: meaning.partOfSpeech || '',
          definition: def.definition,
          example: def.example || '',
        });
        if (senses.length >= 3) break;
      }
      if (senses.length >= 3) break;
    }
    if (senses.length >= 3) break;
  }
  if (!senses.length) return { ok: false, error: 'not-found' };

  const phonetic = data.find((e) => e.phonetic)?.phonetic
    || (data[0].phonetics || []).find((p) => p.text)?.text
    || '';
  const source = (data[0].sourceUrls || [])[0] || '';

  return { ok: true, result: { word: data[0].word || word, phonetic, senses, source } };
}

chrome.runtime.onInstalled.addListener(() => {
  jcRefreshBrand();
  chrome.contextMenus.removeAll(() => {
    chrome.contextMenus.create({
      id: 'explain-selection',
      title: 'Explain with JustClarify',
      contexts: ['selection'],
    });
  });
});

chrome.contextMenus.onClicked.addListener((info, tab) => {
  if (info.menuItemId === 'explain-selection' && tab?.id != null) {
    chrome.tabs.sendMessage(tab.id, { type: 'EXPLAIN_SELECTION' }).catch(() => {});
  }
});

chrome.runtime.onMessage.addListener((msg, _sender, sendResponse) => {
  if (!msg) return;

  if (msg.type === 'ASK_CLAUDE') {
    const originTabId = _sender.tab?.id;
    (async () => {
      try {
        // askEngine streams CLAUDE_PROGRESS messages to the origin tab from
        // whichever engine answers (on-device first, Gateway fallback).
        sendResponse(await askEngine(msg.prompt, msg.reqId, originTabId));
      } catch (error) {
        sendResponse({ ok: false, error: String(error) });
      }
    })();
    return true;
  }

  // Define is a dictionary lookup, not a model answer: a real entry from the
  // Free Dictionary API (dictionaryapi.dev — no key, no account). Fetched here
  // rather than in the content script so a page's CSP can't block it. The
  // caller falls back to the model when a word isn't in the dictionary.
  if (msg.type === 'JC_DICTIONARY') {
    (async () => {
      try {
        sendResponse(await lookupDictionary(msg.word));
      } catch (error) {
        sendResponse({ ok: false, error: String(error) });
      }
    })();
    return true;
  }

  // One highlighted claim → one verdict.
  if (msg.type === 'JC_FACTCHECK_ONE') {
    (async () => {
      try {
        const result = await factCheckOne(msg.claim, msg.context);
        sendResponse(result ? { ok: true, result } : { ok: false, error: 'no-verdict' });
      } catch (error) {
        sendResponse({ ok: false, error: String(error) });
      }
    })();
    return true;
  }

  // A whole article or transcript: extract the check-worthy claims, then verify
  // them. Verdicts stream back as JC_FACTCHECK_RESULT so the page fills in.
  if (msg.type === 'JC_FACTCHECK_TEXT') {
    const originTabId = _sender.tab?.id;
    (async () => {
      try {
        sendResponse(await factCheckText(msg.text, originTabId, msg.runId, msg.limit));
      } catch (error) {
        sendResponse({ ok: false, error: String(error) });
      }
    })();
    return true;
  }

  // --- Live audio fact-checking (experimental) -----------------------------
  // Transcription happens in an offscreen document (service workers can't call
  // getUserMedia). Sentences arrive here as JC_AUDIO_TRANSCRIPT and are batched
  // before being checked — a single spoken line is usually too fragmentary to
  // verify on its own.

  if (msg.type === 'JC_AUDIO_BEGIN') {
    const originTabId = _sender.tab?.id ?? msg.tabId;
    (async () => {
      try {
        sendResponse(await liveAudioBegin(originTabId));
      } catch (error) {
        sendResponse({ ok: false, error: String(error) });
      }
    })();
    return true;
  }

  if (msg.type === 'JC_AUDIO_END') {
    (async () => {
      await liveAudioEnd();
      sendResponse({ ok: true });
    })();
    return true;
  }

  if (msg.type === 'JC_AUDIO_TRANSCRIPT') {
    if (msg.isFinal) liveAudioCollect(msg.text);
    if (liveAudioTabId != null) {
      chrome.tabs
        .sendMessage(liveAudioTabId, { type: 'JC_AUDIO_LINE', text: msg.text, isFinal: msg.isFinal })
        .catch(() => {});
    }
    return;
  }

  if (msg.type === 'JC_AUDIO_ERROR' || msg.type === 'JC_AUDIO_ENDED') {
    if (liveAudioTabId != null) {
      chrome.tabs.sendMessage(liveAudioTabId, msg).catch(() => {});
    }
    if (msg.type === 'JC_AUDIO_ENDED') liveAudioReset();
    return;
  }

  // Which engine will answer, and why — drives the popup's engine card.
  if (msg.type === 'JC_ENGINE_STATUS') {
    (async () => {
      const availability = await onDeviceAvailability();
      const gateway = await gatewayGetSettings();
      const blocked =
        availability === 'unavailable' ? await onDeviceBlockReason() : null;
      sendResponse({
        ok: true,
        availability,
        hasKey: !!gateway,
        model: gateway ? gateway.model : '',
        blocked,
      });
    })();
    return true;
  }

  if (msg.type === 'JC_FACTCHECK_STATUS') {
    (async () => {
      const gateway = await gatewayGetSettings();
      sendResponse({ ok: true, hasKey: !!gateway });
    })();
    return true;
  }
});
